language: go

dist: trusty

go:
  - "1.13"

services:
  - rabbitmq

env:
 - AMQP_URI=amqp://guest:guest@127.0.0.1:5672// GOMAXPROCS=4

before_install:
  - go get -u -buildmode=exe -ldflags "-s -w" golang.org/x/tools/cmd/cover
  - go get -u -buildmode=exe -ldflags "-s -w" github.com/mattn/goveralls
  - go get -u -ldflags "-s -w" github.com/streadway/amqp
  - go get -u -ldflags "-s -w" github.com/mattn/go-sqlite3
  - mkdir -p $HOME/gopath/src/k8s.io && git clone --depth 1 -b v0.4.0 --single-branch -q https://github.com/kubernetes/klog $HOME/gopath/src/k8s.io/klog
  - go get -u -ldflags "-s -w" k8s.io/client-go/...
  - go get -u -ldflags "-s -w" github.com/prometheus/client_golang/prometheus
  - go get -u -ldflags "-s -w" github.com/prometheus/client_golang/prometheus/promhttp
  - mkdir -p $HOME/gopath/src/k8s.io && git clone --depth 1 -b v1.15.3 --single-branch -q https://github.com/kubernetes/kubernetes $HOME/gopath/src/k8s.io/kubernetes

script:
  - go test -v -covermode=count -coverprofile=cover.out --tags=integration ./...

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
