language: go

dist: trusty

go:
  - "1.14"

services:
  - rabbitmq

env:
 - AMQP_URI=amqp://guest:guest@127.0.0.1:5672// GOMAXPROCS=4
 - GO111MODULE=on

before_install:
  - go mod tidy
  - go get -u -buildmode=exe -ldflags "-s -w" golang.org/x/tools/cmd/cover
  - go get -u -buildmode=exe -ldflags "-s -w" github.com/mattn/goveralls
  - mkdir -p $HOME/gopath/src/k8s.io && git clone --depth 1 -b v1.17.3 --single-branch -q https://github.com/kubernetes/kubernetes $HOME/gopath/src/k8s.io/kubernetes


script:
  - go test -v -covermode=count -coverprofile=cover.out --tags=integration ./...

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
